//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsSap.wsPabierta {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="wsPabierta.zcml_pabiertas2_v4")]
    public interface zcml_pabiertas2_v4 {
        
        // CODEGEN: Generating message contract since the operation ZcmlPabiertasV2 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wsSap.wsPabierta.ZcmlPabiertasV2Response1 ZcmlPabiertasV2(wsSap.wsPabierta.ZcmlPabiertasV2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<wsSap.wsPabierta.ZcmlPabiertasV2Response1> ZcmlPabiertasV2Async(wsSap.wsPabierta.ZcmlPabiertasV2Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZcmlPabiertasV21 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pBukrsField;
        
        private string pRanlField;
        
        private ZcmlPabiertasV2[] tPabiertasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PBukrs {
            get {
                return this.pBukrsField;
            }
            set {
                this.pBukrsField = value;
                this.RaisePropertyChanged("PBukrs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PRanl {
            get {
                return this.pRanlField;
            }
            set {
                this.pRanlField = value;
                this.RaisePropertyChanged("PRanl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZcmlPabiertasV2[] TPabiertas {
            get {
                return this.tPabiertasField;
            }
            set {
                this.tPabiertasField = value;
                this.RaisePropertyChanged("TPabiertas");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZcmlPabiertasV2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bukrsField;
        
        private string ranlField;
        
        private string budatField;
        
        private string zfbdtField;
        
        private string belnrField;
        
        private string vbewaField;
        
        private string sgtxtField;
        
        private string shkzgField;
        
        private decimal wrbtrField;
        
        private string waersField;
        
        private decimal dmbtrField;
        
        private string hkontField;
        
        private string rebzgField;
        
        private decimal impReevField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Bukrs {
            get {
                return this.bukrsField;
            }
            set {
                this.bukrsField = value;
                this.RaisePropertyChanged("Bukrs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Ranl {
            get {
                return this.ranlField;
            }
            set {
                this.ranlField = value;
                this.RaisePropertyChanged("Ranl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Budat {
            get {
                return this.budatField;
            }
            set {
                this.budatField = value;
                this.RaisePropertyChanged("Budat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Zfbdt {
            get {
                return this.zfbdtField;
            }
            set {
                this.zfbdtField = value;
                this.RaisePropertyChanged("Zfbdt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Belnr {
            get {
                return this.belnrField;
            }
            set {
                this.belnrField = value;
                this.RaisePropertyChanged("Belnr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Vbewa {
            get {
                return this.vbewaField;
            }
            set {
                this.vbewaField = value;
                this.RaisePropertyChanged("Vbewa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Sgtxt {
            get {
                return this.sgtxtField;
            }
            set {
                this.sgtxtField = value;
                this.RaisePropertyChanged("Sgtxt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Shkzg {
            get {
                return this.shkzgField;
            }
            set {
                this.shkzgField = value;
                this.RaisePropertyChanged("Shkzg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal Wrbtr {
            get {
                return this.wrbtrField;
            }
            set {
                this.wrbtrField = value;
                this.RaisePropertyChanged("Wrbtr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Waers {
            get {
                return this.waersField;
            }
            set {
                this.waersField = value;
                this.RaisePropertyChanged("Waers");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal Dmbtr {
            get {
                return this.dmbtrField;
            }
            set {
                this.dmbtrField = value;
                this.RaisePropertyChanged("Dmbtr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string Hkont {
            get {
                return this.hkontField;
            }
            set {
                this.hkontField = value;
                this.RaisePropertyChanged("Hkont");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string Rebzg {
            get {
                return this.rebzgField;
            }
            set {
                this.rebzgField = value;
                this.RaisePropertyChanged("Rebzg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public decimal ImpReev {
            get {
                return this.impReevField;
            }
            set {
                this.impReevField = value;
                this.RaisePropertyChanged("ImpReev");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZcmlPabiertasV2Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZcmlPabiertasV2[] tPabiertasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZcmlPabiertasV2[] TPabiertas {
            get {
                return this.tPabiertasField;
            }
            set {
                this.tPabiertasField = value;
                this.RaisePropertyChanged("TPabiertas");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZcmlPabiertasV2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public wsSap.wsPabierta.ZcmlPabiertasV21 ZcmlPabiertasV2;
        
        public ZcmlPabiertasV2Request() {
        }
        
        public ZcmlPabiertasV2Request(wsSap.wsPabierta.ZcmlPabiertasV21 ZcmlPabiertasV2) {
            this.ZcmlPabiertasV2 = ZcmlPabiertasV2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZcmlPabiertasV2Response1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public wsSap.wsPabierta.ZcmlPabiertasV2Response ZcmlPabiertasV2Response;
        
        public ZcmlPabiertasV2Response1() {
        }
        
        public ZcmlPabiertasV2Response1(wsSap.wsPabierta.ZcmlPabiertasV2Response ZcmlPabiertasV2Response) {
            this.ZcmlPabiertasV2Response = ZcmlPabiertasV2Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface zcml_pabiertas2_v4Channel : wsSap.wsPabierta.zcml_pabiertas2_v4, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class zcml_pabiertas2_v4Client : System.ServiceModel.ClientBase<wsSap.wsPabierta.zcml_pabiertas2_v4>, wsSap.wsPabierta.zcml_pabiertas2_v4 {
        
        public zcml_pabiertas2_v4Client() {
        }
        
        public zcml_pabiertas2_v4Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public zcml_pabiertas2_v4Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public zcml_pabiertas2_v4Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public zcml_pabiertas2_v4Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsSap.wsPabierta.ZcmlPabiertasV2Response1 wsSap.wsPabierta.zcml_pabiertas2_v4.ZcmlPabiertasV2(wsSap.wsPabierta.ZcmlPabiertasV2Request request) {
            return base.Channel.ZcmlPabiertasV2(request);
        }
        
        public wsSap.wsPabierta.ZcmlPabiertasV2Response ZcmlPabiertasV2(wsSap.wsPabierta.ZcmlPabiertasV21 ZcmlPabiertasV21) {
            wsSap.wsPabierta.ZcmlPabiertasV2Request inValue = new wsSap.wsPabierta.ZcmlPabiertasV2Request();
            inValue.ZcmlPabiertasV2 = ZcmlPabiertasV21;
            wsSap.wsPabierta.ZcmlPabiertasV2Response1 retVal = ((wsSap.wsPabierta.zcml_pabiertas2_v4)(this)).ZcmlPabiertasV2(inValue);
            return retVal.ZcmlPabiertasV2Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsSap.wsPabierta.ZcmlPabiertasV2Response1> wsSap.wsPabierta.zcml_pabiertas2_v4.ZcmlPabiertasV2Async(wsSap.wsPabierta.ZcmlPabiertasV2Request request) {
            return base.Channel.ZcmlPabiertasV2Async(request);
        }
        
        public System.Threading.Tasks.Task<wsSap.wsPabierta.ZcmlPabiertasV2Response1> ZcmlPabiertasV2Async(wsSap.wsPabierta.ZcmlPabiertasV21 ZcmlPabiertasV2) {
            wsSap.wsPabierta.ZcmlPabiertasV2Request inValue = new wsSap.wsPabierta.ZcmlPabiertasV2Request();
            inValue.ZcmlPabiertasV2 = ZcmlPabiertasV2;
            return ((wsSap.wsPabierta.zcml_pabiertas2_v4)(this)).ZcmlPabiertasV2Async(inValue);
        }
    }
}
