//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsSap.wsSolcartera {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="wsSolcartera.ZCMLMF_WF_SOLCARTERA_V8")]
    public interface ZCMLMF_WF_SOLCARTERA_V8 {
        
        // CODEGEN: Generating message contract since the operation ZCMLMF_SOLCARTERA is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wsSap.wsSolcartera.ZCMLMF_SOLCARTERAResponse1 ZCMLMF_SOLCARTERA(wsSap.wsSolcartera.ZCMLMF_SOLCARTERARequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<wsSap.wsSolcartera.ZCMLMF_SOLCARTERAResponse1> ZCMLMF_SOLCARTERAAsync(wsSap.wsSolcartera.ZCMLMF_SOLCARTERARequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZCMLMF_SOLCARTERA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZCML_DETSOLCART[] t_DETSOLCARTField;
        
        private ZCML_DETSOLCART[] t_ENT_DETSOLCARTField;
        
        private ZCML_SOLCARTERA[] t_ENT_SOLCARTERAField;
        
        private ZCML_SOLCARTERA[] t_SOLCARTERAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZCML_DETSOLCART[] T_DETSOLCART {
            get {
                return this.t_DETSOLCARTField;
            }
            set {
                this.t_DETSOLCARTField = value;
                this.RaisePropertyChanged("T_DETSOLCART");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZCML_DETSOLCART[] T_ENT_DETSOLCART {
            get {
                return this.t_ENT_DETSOLCARTField;
            }
            set {
                this.t_ENT_DETSOLCARTField = value;
                this.RaisePropertyChanged("T_ENT_DETSOLCART");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZCML_SOLCARTERA[] T_ENT_SOLCARTERA {
            get {
                return this.t_ENT_SOLCARTERAField;
            }
            set {
                this.t_ENT_SOLCARTERAField = value;
                this.RaisePropertyChanged("T_ENT_SOLCARTERA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZCML_SOLCARTERA[] T_SOLCARTERA {
            get {
                return this.t_SOLCARTERAField;
            }
            set {
                this.t_SOLCARTERAField = value;
                this.RaisePropertyChanged("T_SOLCARTERA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZCML_DETSOLCART : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string zTIPOField;
        
        private string zSOLICITUDField;
        
        private string rANLField;
        
        private string bELNRField;
        
        private decimal dMBTRField;
        
        private decimal wRBTRField;
        
        private string vBEWAField;
        
        private string rEBZGField;
        
        private string zEST_DETSOLField;
        
        private decimal zIMP_PAR_MONCREDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ZTIPO {
            get {
                return this.zTIPOField;
            }
            set {
                this.zTIPOField = value;
                this.RaisePropertyChanged("ZTIPO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ZSOLICITUD {
            get {
                return this.zSOLICITUDField;
            }
            set {
                this.zSOLICITUDField = value;
                this.RaisePropertyChanged("ZSOLICITUD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string RANL {
            get {
                return this.rANLField;
            }
            set {
                this.rANLField = value;
                this.RaisePropertyChanged("RANL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string BELNR {
            get {
                return this.bELNRField;
            }
            set {
                this.bELNRField = value;
                this.RaisePropertyChanged("BELNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal DMBTR {
            get {
                return this.dMBTRField;
            }
            set {
                this.dMBTRField = value;
                this.RaisePropertyChanged("DMBTR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal WRBTR {
            get {
                return this.wRBTRField;
            }
            set {
                this.wRBTRField = value;
                this.RaisePropertyChanged("WRBTR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string VBEWA {
            get {
                return this.vBEWAField;
            }
            set {
                this.vBEWAField = value;
                this.RaisePropertyChanged("VBEWA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string REBZG {
            get {
                return this.rEBZGField;
            }
            set {
                this.rEBZGField = value;
                this.RaisePropertyChanged("REBZG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string ZEST_DETSOL {
            get {
                return this.zEST_DETSOLField;
            }
            set {
                this.zEST_DETSOLField = value;
                this.RaisePropertyChanged("ZEST_DETSOL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal ZIMP_PAR_MONCRED {
            get {
                return this.zIMP_PAR_MONCREDField;
            }
            set {
                this.zIMP_PAR_MONCREDField = value;
                this.RaisePropertyChanged("ZIMP_PAR_MONCRED");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZCML_SOLCARTERA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string zTIPOField;
        
        private string zSOLICITUDField;
        
        private string zFEC_SOLICField;
        
        private string bUKRSField;
        
        private string rANLField;
        
        private string zFEC_ULTESTField;
        
        private string zUSERField;
        
        private string zEST_SOLCARField;
        
        private decimal zPROMESA_PAGOField;
        
        private string zFEC_PROMESAField;
        
        private decimal zMTO_DESC_MAXField;
        
        private decimal zMTO_DESC_CONVField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ZTIPO {
            get {
                return this.zTIPOField;
            }
            set {
                this.zTIPOField = value;
                this.RaisePropertyChanged("ZTIPO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ZSOLICITUD {
            get {
                return this.zSOLICITUDField;
            }
            set {
                this.zSOLICITUDField = value;
                this.RaisePropertyChanged("ZSOLICITUD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ZFEC_SOLIC {
            get {
                return this.zFEC_SOLICField;
            }
            set {
                this.zFEC_SOLICField = value;
                this.RaisePropertyChanged("ZFEC_SOLIC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string BUKRS {
            get {
                return this.bUKRSField;
            }
            set {
                this.bUKRSField = value;
                this.RaisePropertyChanged("BUKRS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string RANL {
            get {
                return this.rANLField;
            }
            set {
                this.rANLField = value;
                this.RaisePropertyChanged("RANL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ZFEC_ULTEST {
            get {
                return this.zFEC_ULTESTField;
            }
            set {
                this.zFEC_ULTESTField = value;
                this.RaisePropertyChanged("ZFEC_ULTEST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ZUSER {
            get {
                return this.zUSERField;
            }
            set {
                this.zUSERField = value;
                this.RaisePropertyChanged("ZUSER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string ZEST_SOLCAR {
            get {
                return this.zEST_SOLCARField;
            }
            set {
                this.zEST_SOLCARField = value;
                this.RaisePropertyChanged("ZEST_SOLCAR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal ZPROMESA_PAGO {
            get {
                return this.zPROMESA_PAGOField;
            }
            set {
                this.zPROMESA_PAGOField = value;
                this.RaisePropertyChanged("ZPROMESA_PAGO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ZFEC_PROMESA {
            get {
                return this.zFEC_PROMESAField;
            }
            set {
                this.zFEC_PROMESAField = value;
                this.RaisePropertyChanged("ZFEC_PROMESA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal ZMTO_DESC_MAX {
            get {
                return this.zMTO_DESC_MAXField;
            }
            set {
                this.zMTO_DESC_MAXField = value;
                this.RaisePropertyChanged("ZMTO_DESC_MAX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public decimal ZMTO_DESC_CONV {
            get {
                return this.zMTO_DESC_CONVField;
            }
            set {
                this.zMTO_DESC_CONVField = value;
                this.RaisePropertyChanged("ZMTO_DESC_CONV");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZCMLMF_SOLCARTERAResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int eRRORField;
        
        private ZCML_DETSOLCART[] t_DETSOLCARTField;
        
        private ZCML_DETSOLCART[] t_ENT_DETSOLCARTField;
        
        private ZCML_SOLCARTERA[] t_ENT_SOLCARTERAField;
        
        private ZCML_SOLCARTERA[] t_SOLCARTERAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int ERROR {
            get {
                return this.eRRORField;
            }
            set {
                this.eRRORField = value;
                this.RaisePropertyChanged("ERROR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZCML_DETSOLCART[] T_DETSOLCART {
            get {
                return this.t_DETSOLCARTField;
            }
            set {
                this.t_DETSOLCARTField = value;
                this.RaisePropertyChanged("T_DETSOLCART");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZCML_DETSOLCART[] T_ENT_DETSOLCART {
            get {
                return this.t_ENT_DETSOLCARTField;
            }
            set {
                this.t_ENT_DETSOLCARTField = value;
                this.RaisePropertyChanged("T_ENT_DETSOLCART");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZCML_SOLCARTERA[] T_ENT_SOLCARTERA {
            get {
                return this.t_ENT_SOLCARTERAField;
            }
            set {
                this.t_ENT_SOLCARTERAField = value;
                this.RaisePropertyChanged("T_ENT_SOLCARTERA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZCML_SOLCARTERA[] T_SOLCARTERA {
            get {
                return this.t_SOLCARTERAField;
            }
            set {
                this.t_SOLCARTERAField = value;
                this.RaisePropertyChanged("T_SOLCARTERA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZCMLMF_SOLCARTERARequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public wsSap.wsSolcartera.ZCMLMF_SOLCARTERA ZCMLMF_SOLCARTERA;
        
        public ZCMLMF_SOLCARTERARequest() {
        }
        
        public ZCMLMF_SOLCARTERARequest(wsSap.wsSolcartera.ZCMLMF_SOLCARTERA ZCMLMF_SOLCARTERA) {
            this.ZCMLMF_SOLCARTERA = ZCMLMF_SOLCARTERA;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZCMLMF_SOLCARTERAResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public wsSap.wsSolcartera.ZCMLMF_SOLCARTERAResponse ZCMLMF_SOLCARTERAResponse;
        
        public ZCMLMF_SOLCARTERAResponse1() {
        }
        
        public ZCMLMF_SOLCARTERAResponse1(wsSap.wsSolcartera.ZCMLMF_SOLCARTERAResponse ZCMLMF_SOLCARTERAResponse) {
            this.ZCMLMF_SOLCARTERAResponse = ZCMLMF_SOLCARTERAResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZCMLMF_WF_SOLCARTERA_V8Channel : wsSap.wsSolcartera.ZCMLMF_WF_SOLCARTERA_V8, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZCMLMF_WF_SOLCARTERA_V8Client : System.ServiceModel.ClientBase<wsSap.wsSolcartera.ZCMLMF_WF_SOLCARTERA_V8>, wsSap.wsSolcartera.ZCMLMF_WF_SOLCARTERA_V8 {
        
        public ZCMLMF_WF_SOLCARTERA_V8Client() {
        }
        
        public ZCMLMF_WF_SOLCARTERA_V8Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZCMLMF_WF_SOLCARTERA_V8Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZCMLMF_WF_SOLCARTERA_V8Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZCMLMF_WF_SOLCARTERA_V8Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsSap.wsSolcartera.ZCMLMF_SOLCARTERAResponse1 wsSap.wsSolcartera.ZCMLMF_WF_SOLCARTERA_V8.ZCMLMF_SOLCARTERA(wsSap.wsSolcartera.ZCMLMF_SOLCARTERARequest request) {
            return base.Channel.ZCMLMF_SOLCARTERA(request);
        }
        
        public wsSap.wsSolcartera.ZCMLMF_SOLCARTERAResponse ZCMLMF_SOLCARTERA(wsSap.wsSolcartera.ZCMLMF_SOLCARTERA ZCMLMF_SOLCARTERA1) {
            wsSap.wsSolcartera.ZCMLMF_SOLCARTERARequest inValue = new wsSap.wsSolcartera.ZCMLMF_SOLCARTERARequest();
            inValue.ZCMLMF_SOLCARTERA = ZCMLMF_SOLCARTERA1;
            wsSap.wsSolcartera.ZCMLMF_SOLCARTERAResponse1 retVal = ((wsSap.wsSolcartera.ZCMLMF_WF_SOLCARTERA_V8)(this)).ZCMLMF_SOLCARTERA(inValue);
            return retVal.ZCMLMF_SOLCARTERAResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsSap.wsSolcartera.ZCMLMF_SOLCARTERAResponse1> wsSap.wsSolcartera.ZCMLMF_WF_SOLCARTERA_V8.ZCMLMF_SOLCARTERAAsync(wsSap.wsSolcartera.ZCMLMF_SOLCARTERARequest request) {
            return base.Channel.ZCMLMF_SOLCARTERAAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsSap.wsSolcartera.ZCMLMF_SOLCARTERAResponse1> ZCMLMF_SOLCARTERAAsync(wsSap.wsSolcartera.ZCMLMF_SOLCARTERA ZCMLMF_SOLCARTERA) {
            wsSap.wsSolcartera.ZCMLMF_SOLCARTERARequest inValue = new wsSap.wsSolcartera.ZCMLMF_SOLCARTERARequest();
            inValue.ZCMLMF_SOLCARTERA = ZCMLMF_SOLCARTERA;
            return ((wsSap.wsSolcartera.ZCMLMF_WF_SOLCARTERA_V8)(this)).ZCMLMF_SOLCARTERAAsync(inValue);
        }
    }
}
